[versions]
appcompat = "1.3.1"
material = "1.4.0-rc01"
activity = "1.2.4"
constraintlayout = "2.0.4"
junit = "4.13.2"
ext_junit = "1.1.2"
glide = "4.8.0"
gson = "2.8.7"
espresso = "3.4.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
ext_junit = { module = "androidx.test.ext:junit", version.ref = "ext_junit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

